"use client";

import { create } from "zustand";
import { persist, type PersistStorage, type StorageValue } from "zustand/middleware";
import type { DeepResearchReport } from "@/types/research";

/**
 * Client-side store for Deep Research reports.
 *
 * Reports are keyed by `id` (the nanoid generated by the orchestrator) and
 * also indexed by `productId` so the product detail page can look them up.
 * Persisted to localStorage under `wynner.research.v1`.
 */

type ResearchState = {
  /** id → report */
  reports: Record<string, DeepResearchReport>;
  /** productId → reportId — most recent wins */
  byProduct: Record<string, string>;

  addReport: (report: DeepResearchReport) => void;
  getById: (id: string) => DeepResearchReport | undefined;
  getByProductId: (productId: string) => DeepResearchReport | undefined;
  removeReport: (id: string) => void;
  resetReports: () => void;
};

const storage: PersistStorage<Pick<ResearchState, "reports" | "byProduct">> = {
  getItem: (name) => {
    if (typeof window === "undefined") return null;
    const raw = window.localStorage.getItem(name);
    if (!raw) return null;
    try {
      return JSON.parse(raw) as StorageValue<Pick<ResearchState, "reports" | "byProduct">>;
    } catch {
      return null;
    }
  },
  setItem: (name, value) => {
    if (typeof window === "undefined") return;
    window.localStorage.setItem(name, JSON.stringify(value));
  },
  removeItem: (name) => {
    if (typeof window === "undefined") return;
    window.localStorage.removeItem(name);
  },
};

export const useResearchStore = create<ResearchState>()(
  persist(
    (set, get) => ({
      reports: {},
      byProduct: {},

      addReport: (report) =>
        set((s) => ({
          reports: { ...s.reports, [report.id]: report },
          byProduct: report.productId
            ? { ...s.byProduct, [report.productId]: report.id }
            : s.byProduct,
        })),

      getById: (id) => get().reports[id],

      getByProductId: (productId) => {
        const rid = get().byProduct[productId];
        return rid ? get().reports[rid] : undefined;
      },

      removeReport: (id) =>
        set((s) => {
          // Build a copy of `reports` without `id` — using delete avoids the
          // unused-destructure-var lint while keeping the immutability we want.
          const reports = { ...s.reports };
          delete reports[id];
          const byProduct = { ...s.byProduct };
          for (const [pid, rid] of Object.entries(byProduct)) {
            if (rid === id) delete byProduct[pid];
          }
          return { reports, byProduct };
        }),

      resetReports: () => set({ reports: {}, byProduct: {} }),
    }),
    {
      name: "wynner.research.v1",
      storage,
      partialize: (s) => ({ reports: s.reports, byProduct: s.byProduct }),
    },
  ),
);
