"use client";

import { motion, useReducedMotion } from "framer-motion";
import { ArrowRight, Heart, LayoutGrid, List, Newspaper } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { ScoreNumber } from "@/components/animated/score-number";
import { SectionHeader, STAGGER_ITEM_VARIANTS, StaggerGrid, StaggerItem } from "./editorial-primitives";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { NICHES } from "@/lib/data/niches";
import { COUNTRIES } from "@/lib/data/countries";
import { useProductStore } from "@/lib/store/products";
import type { Product, Verdict } from "@/types";
import { cn } from "@/lib/utils";

const VERDICT_COLOR: Record<Verdict, string> = {
  go: "#3DD68C",
  test: "#FFAB40",
  risky: "#FF7E5F",
  skip: "#FF5C7C",
};

type GalleryView = "editorial" | "grid" | "compact";

type Props = {
  /** Curated picks for the day. Already sorted high→low; we slice into rows. */
  picks: Product[];
  /** Editorial title generated by Gemini, or a graceful fallback. */
  editorialTitle: string;
  sectionId: string;
  /** Optional 2-sentence "pitch" for pick #1, generated by Gemini in the briefing. */
  pickOnePitch?: string;
};

export function PicksGallery({
  picks,
  editorialTitle,
  sectionId,
  pickOnePitch,
}: Props) {
  const [view, setView] = useState<GalleryView>("editorial");
  const headliner = picks[0];
  const pair = picks.slice(1, 3);
  const quartet = picks.slice(3, 7);
  const tail = picks.slice(7);

  return (
    <section className="pt-32 md:pt-40">
      <div className="mx-auto w-full max-w-7xl px-6 md:px-12">
        <div className="relative">
          <SectionHeader
            id={sectionId}
            kicker="TODAY'S PICKS · CURATED FOR YOU"
            headline={editorialTitle}
            subHeadline={`${picks.length} product${picks.length === 1 ? "" : "s"} our AI thinks you should look at today`}
          />
          <div className="absolute right-0 top-3 hidden md:block">
            <ViewSwitcher view={view} onChange={setView} />
          </div>
        </div>

        {picks.length === 0 ? (
          <EmptyPicks />
        ) : view === "grid" ? (
          <UniformGrid picks={picks} />
        ) : view === "compact" ? (
          <CompactList picks={picks} />
        ) : (
          <StaggerGrid className="space-y-6">
            {headliner && (
              <StaggerItem>
                <HeadlinerCard product={headliner} pitch={pickOnePitch} />
              </StaggerItem>
            )}
            {pair.length > 0 && (
              <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
                {pair.map((p) => (
                  <StaggerItem key={p.id}>
                    <PairCard product={p} />
                  </StaggerItem>
                ))}
              </div>
            )}
            {quartet.length > 0 && (
              <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
                {quartet.map((p) => (
                  <StaggerItem key={p.id}>
                    <QuartetCard product={p} />
                  </StaggerItem>
                ))}
              </div>
            )}
            {tail.length > 0 && (
              <StaggerItem>
                <TailScroll picks={tail} />
              </StaggerItem>
            )}
          </StaggerGrid>
        )}
      </div>
    </section>
  );
}

/* -------------------------------------------------------------------------- */

function ViewSwitcher({
  view,
  onChange,
}: {
  view: GalleryView;
  onChange: (v: GalleryView) => void;
}) {
  return (
    <div className="inline-flex items-center gap-1 rounded-full bg-surface/70 p-1 backdrop-blur-md">
      <ViewBtn current={view} value="editorial" onClick={onChange} icon={Newspaper} />
      <ViewBtn current={view} value="grid" onClick={onChange} icon={LayoutGrid} />
      <ViewBtn current={view} value="compact" onClick={onChange} icon={List} />
    </div>
  );
}

function ViewBtn({
  current,
  value,
  onClick,
  icon: Icon,
}: {
  current: GalleryView;
  value: GalleryView;
  onClick: (v: GalleryView) => void;
  icon: typeof Newspaper;
}) {
  const active = current === value;
  return (
    <button
      type="button"
      aria-label={value}
      onClick={() => onClick(value)}
      className={cn(
        "inline-flex h-7 w-7 items-center justify-center rounded-full transition-all",
        active
          ? "bg-surface text-text shadow-sm"
          : "text-text-muted hover:text-text",
      )}
    >
      <Icon className="h-3.5 w-3.5" />
    </button>
  );
}

/* -------------------------------------------------------------------------- */

function HeadlinerCard({ product, pitch }: { product: Product; pitch?: string }) {
  return (
    <CardWrap product={product} heightClass="h-auto md:h-96">
      <div className="grid h-full grid-cols-1 md:grid-cols-[60%_40%]">
        <div className="relative h-64 md:h-full">
          {product.image && (
            <Image
              src={product.image}
              alt={product.name}
              fill
              sizes="(max-width: 768px) 100vw, 60vw"
              className="object-cover"
            />
          )}
          <FavoriteHeart productId={product.id} />
        </div>
        <div className="flex flex-col justify-between p-6 md:p-8">
          <div>
            <span className="font-mono text-[10px] uppercase tracking-[0.2em] text-text-dim">
              Pick #1
            </span>
            <h3 className="mt-3 font-serif text-3xl leading-tight text-text md:text-4xl">
              {product.name}
            </h3>
            <p className="mt-3 text-sm leading-relaxed text-text-muted md:text-[15px]">
              {pitch ?? defaultPitch(product)}
            </p>
          </div>
          <div className="mt-6 space-y-3">
            <MetadataRow product={product} />
            <Link
              href={`/product/${product.id}`}
              className="inline-flex items-center gap-1.5 text-sm font-medium text-aurora-purple hover:text-aurora-pink"
            >
              Open dossier <ArrowRight className="h-3.5 w-3.5" />
            </Link>
          </div>
        </div>
      </div>
    </CardWrap>
  );
}

function PairCard({ product }: { product: Product }) {
  return (
    <CardWrap product={product} heightClass="h-auto md:h-80">
      <div className="grid h-full grid-cols-[50%_50%]">
        <div className="relative h-full min-h-[180px]">
          {product.image && (
            <Image
              src={product.image}
              alt={product.name}
              fill
              sizes="(max-width: 1024px) 50vw, 25vw"
              className="object-cover"
            />
          )}
          <FavoriteHeart productId={product.id} />
        </div>
        <div className="flex flex-col justify-between p-5">
          <div>
            <span className="font-mono text-[10px] uppercase tracking-[0.2em] text-text-dim">
              Pick
            </span>
            <h3 className="mt-2 font-serif text-2xl leading-tight text-text">
              {product.name}
            </h3>
          </div>
          <MetadataRow product={product} compact />
        </div>
      </div>
    </CardWrap>
  );
}

function QuartetCard({ product }: { product: Product }) {
  return (
    <CardWrap product={product} heightClass="h-72">
      <div className="flex h-full flex-col">
        <div className="relative h-40 w-full overflow-hidden">
          {product.image && (
            <Image
              src={product.image}
              alt={product.name}
              fill
              sizes="(max-width: 768px) 50vw, 25vw"
              className="object-cover"
            />
          )}
          <FavoriteHeart productId={product.id} />
        </div>
        <div className="flex flex-1 flex-col justify-between p-4">
          <h3 className="line-clamp-2 font-serif text-base leading-tight text-text">
            {product.name}
          </h3>
          <MetadataRow product={product} compact />
        </div>
      </div>
    </CardWrap>
  );
}

function TailScroll({ picks }: { picks: Product[] }) {
  return (
    <div className="relative">
      <div className="mb-3 font-mono text-[10px] uppercase tracking-[0.2em] text-text-dim">
        The long tail · {picks.length} more
      </div>
      <div className="-mx-1 flex snap-x snap-mandatory gap-3 overflow-x-auto px-1 pb-2 hide-scrollbar">
        {picks.map((p) => (
          <TailCard key={p.id} product={p} />
        ))}
      </div>
      {/* Gradient fade masks */}
      <div className="pointer-events-none absolute inset-y-0 left-0 w-8 bg-gradient-to-r from-[#FCFCFD] to-transparent dark:from-[#0A0B1F]" />
      <div className="pointer-events-none absolute inset-y-0 right-0 w-8 bg-gradient-to-l from-[#FCFCFD] to-transparent dark:from-[#0A0B1F]" />
    </div>
  );
}

function TailCard({ product }: { product: Product }) {
  return (
    <Link
      href={`/product/${product.id}`}
      className="block w-52 shrink-0 snap-start"
    >
      <div className="overflow-hidden rounded-2xl border border-border-soft bg-surface/70 backdrop-blur-md transition-colors hover:border-aurora-purple/45">
        <div className="relative aspect-[5/6] w-full bg-surface-elevated">
          {product.image && (
            <Image
              src={product.image}
              alt={product.name}
              fill
              sizes="208px"
              className="object-cover"
            />
          )}
        </div>
        <div className="p-3">
          <div className="line-clamp-1 text-xs font-medium text-text">{product.name}</div>
          <div className="mt-1 flex items-center justify-between text-[10px] text-text-muted">
            <span>{NICHES[product.category]?.label}</span>
            <span
              className="font-mono font-medium"
              style={{ color: VERDICT_COLOR[product.verdict] }}
            >
              {product.sellScore}
            </span>
          </div>
        </div>
      </div>
    </Link>
  );
}

/* -------------------------------------------------------------------------- */
/* Shared bits                                                                 */
/* -------------------------------------------------------------------------- */

function CardWrap({
  product,
  heightClass,
  children,
}: {
  product: Product;
  heightClass: string;
  children: React.ReactNode;
}) {
  const reduce = useReducedMotion();
  const verdictColor = VERDICT_COLOR[product.verdict];
  return (
    <motion.article
      variants={STAGGER_ITEM_VARIANTS}
      whileHover={reduce ? undefined : { y: -6, scale: 1.015 }}
      transition={{ type: "spring", stiffness: 220, damping: 22 }}
      className={cn(
        "group relative overflow-hidden rounded-[24px] border border-border-soft bg-surface/70 backdrop-blur-md transition-shadow",
        heightClass,
      )}
      style={{
        boxShadow: `0 0 0 1px ${verdictColor}22, 0 18px 40px -24px ${verdictColor}55`,
      }}
    >
      <Link
        href={`/product/${product.id}`}
        aria-label={`Open ${product.name}`}
        className="absolute inset-0 z-0"
      />
      <div className="relative z-10 h-full">{children}</div>
    </motion.article>
  );
}

function MetadataRow({ product, compact }: { product: Product; compact?: boolean }) {
  const niche = NICHES[product.category];
  const country = COUNTRIES[product.targetCountry];
  return (
    <div
      className={cn(
        "flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px] text-text-muted",
        compact && "gap-x-2",
      )}
    >
      <span className="flex items-center gap-1.5">
        <span
          className="h-1.5 w-1.5 rounded-full"
          style={{ backgroundColor: niche?.color ?? "#A788FF" }}
        />
        <span>{niche?.label ?? product.category}</span>
      </span>
      {!compact && <span aria-hidden>·</span>}
      <span>
        {country?.flag ?? "🌐"} {country?.code ?? product.targetCountry}
      </span>
      <span aria-hidden>·</span>
      <span
        className="font-mono font-medium"
        style={{ color: VERDICT_COLOR[product.verdict] }}
      >
        <ScoreNumber value={product.sellScore} className="font-mono" /> · {product.verdict.toUpperCase()}
      </span>
    </div>
  );
}

function FavoriteHeart({ productId }: { productId: string }) {
  const favorites = useProductStore((s) => s.favorites);
  const toggleFavorite = useProductStore((s) => s.toggleFavorite);
  const fav = favorites instanceof Set ? favorites.has(productId) : false;
  return (
    <button
      type="button"
      onClick={(e) => {
        e.preventDefault();
        e.stopPropagation();
        toggleFavorite(productId);
      }}
      aria-label={fav ? "Unfavorite" : "Favorite"}
      className="absolute right-3 top-3 z-20 inline-flex h-9 w-9 items-center justify-center rounded-full bg-white/80 text-text backdrop-blur-md transition-all hover:scale-110 dark:bg-black/40 dark:text-white"
    >
      <motion.span
        animate={{ scale: fav ? [1, 1.3, 1] : 1 }}
        transition={{ duration: 0.4, ease: [0.22, 1, 0.36, 1] }}
      >
        <Heart
          className={cn("h-4 w-4", fav && "fill-aurora-pink text-aurora-pink")}
        />
      </motion.span>
    </button>
  );
}

function defaultPitch(p: Product): string {
  const niche = NICHES[p.category]?.label.toLowerCase();
  const country = COUNTRIES[p.targetCountry]?.name;
  return `Scored ${p.sellScore} against ${p.verdict.toUpperCase()} threshold, with ${niche ?? "category"} demand signal and ${country ?? "target market"} fit doing most of the work.`;
}

/* -------------------------------------------------------------------------- */
/* Alternative views                                                           */
/* -------------------------------------------------------------------------- */

function UniformGrid({ picks }: { picks: Product[] }) {
  return (
    <StaggerGrid className="grid grid-cols-2 gap-4 md:grid-cols-4">
      {picks.map((p) => (
        <StaggerItem key={p.id}>
          <QuartetCard product={p} />
        </StaggerItem>
      ))}
    </StaggerGrid>
  );
}

function CompactList({ picks }: { picks: Product[] }) {
  return (
    <StaggerGrid className="divide-y divide-border-soft overflow-hidden rounded-3xl border border-border-soft bg-surface/70 backdrop-blur-md">
      {picks.map((p) => (
        <StaggerItem key={p.id} as="div">
          <Link
            href={`/product/${p.id}`}
            className="grid grid-cols-[60px_1fr_120px_80px] items-center gap-4 px-4 py-3 transition-colors hover:bg-surface/40"
          >
            <div className="relative h-12 w-12 overflow-hidden rounded-md bg-surface-elevated">
              {p.image && (
                <Image src={p.image} alt={p.name} fill sizes="48px" className="object-cover" />
              )}
            </div>
            <div className="min-w-0">
              <div className="truncate text-sm text-text">{p.name}</div>
              <div className="font-mono text-[10px] text-text-dim">
                {NICHES[p.category]?.label} · {COUNTRIES[p.targetCountry]?.flag}
              </div>
            </div>
            <span className="font-mono text-xs tabular-nums text-text-muted">
              {p.verdict.toUpperCase()}
            </span>
            <span
              className="text-right font-mono text-sm font-medium tabular-nums"
              style={{ color: VERDICT_COLOR[p.verdict] }}
            >
              {p.sellScore}
            </span>
          </Link>
        </StaggerItem>
      ))}
    </StaggerGrid>
  );
}

function EmptyPicks() {
  return (
    <div className="glass rounded-3xl p-12 text-center">
      <p className="font-serif text-2xl italic text-text">
        Today&apos;s picks unlock after you&apos;ve scored a few products.
      </p>
      <p className="mt-2 text-sm text-text-muted">
        Score 5+ products and we&apos;ll curate a daily set for you.
      </p>
      <Link
        href="/scan"
        className="mt-5 inline-flex h-10 items-center gap-1.5 rounded-full px-5 text-sm font-medium text-white"
        style={{ background: "linear-gradient(135deg, #5B8DFF, #A788FF, #FF89C5)" }}
      >
        Start a scan
      </Link>
    </div>
  );
}

/* Wrapper for `Tooltip` so eslint doesn't complain about unused exports.
 * Used by future "How we chose these →" tooltip; left as a no-op now. */
export function HowWeChose({ children }: { children: React.ReactNode }) {
  return (
    <Tooltip>
      <TooltipTrigger asChild>{children}</TooltipTrigger>
      <TooltipContent className="max-w-xs text-xs">
        Picks are sorted by sell-score, weighted by your favorite niches and
        countries. Updated daily.
      </TooltipContent>
    </Tooltip>
  );
}
